version: "3"

services:
  app:
    build:
      context: ./app
      args:
        APP_PORT: ${APP_PORT}
    environment:
      env_file: ./app/.env
      NODE_ENV: development
      PORT: ${APP_PORT}
    volumes:
      - ./app:/usr/src/app
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    links:
      - server
    command: npm start

  server:
    depends_on:
      - mongodb
    links:
      - mongodb
    build:
      context: ./server
      args:
        SERVER_PORT: ${SERVER_PORT}
    environment:
      NODE_ENV: development
      MONGO_URL: ${DB_HOST_PORT}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - ./server:/usr/src/server:rw
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_PORT}"
    command: npm start

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      env_file: ./db/.env
    volumes:
      - mongodb_data:/data/db
      - ./db/backup:/data/backup

volumes:
  mongodb_data: {}
